### PR TITLE
added jshint to package scripts to run npm run lint fixes #54

### LINKED ISSUE #54: add simple linter pass
to check for unused vars and complexity analysis

### PR DESCRIPTION
**Pull request by JasonWeathersby**

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
cool, do we need some kind of dot file with a list of our rules?
http://jshint.com/docs/options/#maxcomplexity

**Comment by JasonWeathersby** [comment]
added config to package.json

**Comment by JasonWeathersby** [comment]
without || true the jshint return code is causing npm to complain.

**Comment by nickdesaulniers** [comment]
cool thank you! :fireworks:

**Pull request merged**
